### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by tekinengin** [caelan/SS-Replan#1]
Hi, 

I try to run `python run_pybullet.py -problem detect_block` but i get the following. Is it possible to provide `kitchen_part_right_gen_convex.urdf`?

```
(pl) XXX:~/SS-Replan$ python run_pybullet.py -problem detect_block
pybullet build time: Dec  5 2022 18:28:03
Use Track IK: False
Tasks: ['detect_block', 'hold_block', 'inspect_drawer', 'swap_drawers', 'sugar_drawer', 'cook_block', 'stow_block']
Random seed: 2147483648
Numpy seed: 2147483648
No display detected!
/home/user/SS-Replan/src/../models/kitchen_description/urdf/kitchen_part_right_gen_convex.urdf
Traceback (most recent call last):
  File "/home/user/SS-Replan/run_pybullet.py", line 126, in <module>
    main()
  File "/home/user/SS-Replan/run_pybullet.py", line 76, in main
    world = World(use_gui=True)
  File "/home/user/SS-Replan/src/world.py", line 95, in __init__
    self.kitchen = load_pybullet(KITCHEN_PATH, fixed_base=True, cylinder=True)
  File "/home/user/SS-Replan/ss-pybullet/pybullet_tools/utils.py", line 512, in load_pybullet
    body = p.loadURDF(filename, useFixedBase=fixed_base, flags=flags,
pybullet.error: Cannot load URDF file.
```

**Comment by zhang-bo7** [comment]
> Hi,
> 
> I try to run `python run_pybullet.py -problem detect_block` but i get the following. Is it possible to provide `kitchen_part_right_gen_convex.urdf`?
> 
> ```
> (pl) XXX:~/SS-Replan$ python run_pybullet.py -problem detect_block
> pybullet build time: Dec  5 2022 18:28:03
> Use Track IK: False
> Tasks: ['detect_block', 'hold_block', 'inspect_drawer', 'swap_drawers', 'sugar_drawer', 'cook_block', 'stow_block']
> Random seed: 2147483648
> Numpy seed: 2147483648
> No display detected!
> /home/user/SS-Replan/src/../models/kitchen_description/urdf/kitchen_part_right_gen_convex.urdf
> Traceback (most recent call last):
>   File "/home/user/SS-Replan/run_pybullet.py", line 126, in <module>
>     main()
>   File "/home/user/SS-Replan/run_pybullet.py", line 76, in main
>     world = World(use_gui=True)
>   File "/home/user/SS-Replan/src/world.py", line 95, in __init__
>     self.kitchen = load_pybullet(KITCHEN_PATH, fixed_base=True, cylinder=True)
>   File "/home/user/SS-Replan/ss-pybullet/pybullet_tools/utils.py", line 512, in load_pybullet
>     body = p.loadURDF(filename, useFixedBase=fixed_base, flags=flags,
> pybullet.error: Cannot load URDF file.
> ```
Hello, I also encountered the same problem, may I ask you to solve it

**Comment by Tianyi20** [comment]
> > Hi,
> > I try to run `python run_pybullet.py -problem detect_block` but i get the following. Is it possible to provide `kitchen_part_right_gen_convex.urdf`?
> > ```
> > (pl) XXX:~/SS-Replan$ python run_pybullet.py -problem detect_block
> > pybullet build time: Dec  5 2022 18:28:03
> > Use Track IK: False
> > Tasks: ['detect_block', 'hold_block', 'inspect_drawer', 'swap_drawers', 'sugar_drawer', 'cook_block', 'stow_block']
> > Random seed: 2147483648
> > Numpy seed: 2147483648
> > No display detected!
> > /home/user/SS-Replan/src/../models/kitchen_description/urdf/kitchen_part_right_gen_convex.urdf
> > Traceback (most recent call last):
> >   File "/home/user/SS-Replan/run_pybullet.py", line 126, in <module>
> >     main()
> >   File "/home/user/SS-Replan/run_pybullet.py", line 76, in main
> >     world = World(use_gui=True)
> >   File "/home/user/SS-Replan/src/world.py", line 95, in __init__
> >     self.kitchen = load_pybullet(KITCHEN_PATH, fixed_base=True, cylinder=True)
> >   File "/home/user/SS-Replan/ss-pybullet/pybullet_tools/utils.py", line 512, in load_pybullet
> >     body = p.loadURDF(filename, useFixedBase=fixed_base, flags=flags,
> > pybullet.error: Cannot load URDF file.
> > ```
> 
> Hello, I also encountered the same problem, may I ask you to solve it

HI, I also encounter this URDF file missing.Have you solved this problem? Could you share the URDF file to me?
